from config import *
from datetime import datetime

def create_html_report(sbb_data, cab_data, layout_data, cab_stats, output_path, source_filename=""):
    """Generates a rich text HTML report."""
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>LSM Parser Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            h1, h2 {{ color: #333; }}
            table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
            .section {{ margin-bottom: 40px; border: 1px solid #ccc; padding: 15px; border-radius: 5px; }}
            
            /* Colors */
            .bg-green {{ background-color: #{COLOR_GREEN}; }}
            .bg-yellow {{ background-color: #{COLOR_YELLOW}; }}
            .bg-tan {{ background-color: #{COLOR_TAN}; }}
            .bg-violet {{ background-color: #{COLOR_VIOLET}; }}
            .bg-blue {{ background-color: #{COLOR_BLUE}; }}
            .bg-pink {{ background-color: #{COLOR_PINK}; }}
            
            /* Layout Grid */
            .layout-container {{ display: flex; flex-wrap: wrap; gap: 20px; }}
            .sbb-layout {{ border: 1px solid #999; padding: 10px; }}
            .grid {{ display: grid; gap: 2px; background-color: #ccc; border: 1px solid #999; }}
            .cab-cell {{ 
                background-color: #fff; 
                padding: 5px; 
                font-size: 10px; 
                text-align: center; 
                min-width: 60px; 
                min-height: 40px;
                display: flex;
                flex-direction: column;
                justify-content: center;
            }}
        </style>
    </head>
    <body>
        <h1>LSM Parser Report</h1>
        <p><strong>Source File:</strong> {source_filename or 'Unknown'}</p>
        <p>Generated by LSM Parser on {datetime.now().strftime("%m/%d/%Y %H:%M:%S")}</p>
    """
    
    # --- SBB Info ---
    html += '<div class="section"><h2>SBox Information</h2>'
    html += '<table><tr><th>Setting</th>'
    for sbb in sbb_data:
        html += f"<th>{sbb['name_header']} ({sbb['ip']})</th>"
    html += '</tr>'
    
    # Rows
    rows = [
        ("Model", 'model'), ("Serial Number", 'sn'), ("Main Version", 'fw_main'),
        ("Additional Versions", 'fw_add'), ("SBox Name", 'sbb_name')
    ]
    for label, key in rows:
        html += f"<tr><td><b>{label}</b></td>"
        for sbb in sbb_data:
            extra_style = ' style="white-space: normal; word-wrap: break-word; min-width: 150px; max-width: 300px;"' if key == 'fw_add' else ''
            html += f"<td{extra_style}>{sbb.get(key, '')}</td>"
        html += "</tr>"

    # Groups
    html += "<tr><td><b>Group IPs</b></td>"
    for sbb in sbb_data:
        g_str = "<br>".join([f"G{k}: {v}" for k, v in sbb['groups'].items()])
        html += f"<td>{g_str}</td>"
    html += "</tr>"
    
    # VW Mode
    html += "<tr><td><b>Video Wall Mode</b></td>"
    for sbb in sbb_data:
        val = sbb.get('vw_mode', '')
        cls = 'class="bg-green"' if val == "On" else ''
        html += f"<td {cls}>{val}</td>"
    html += "</tr>"
    
    # Video Offset
    html += "<tr><td><b>Video Offset</b></td>"
    for sbb in sbb_data:
        html += f"<td>{sbb.get('video_offset', '')}</td>"
    html += "</tr>"
    
    # Cabinet Layout
    html += "<tr><td><b>Cabinet Layout</b></td>"
    for sbb in sbb_data:
        html += f"<td>{sbb.get('layout_str', '')}</td>"
    html += "</tr>"

    # SBox Output Resolution
    html += "<tr><td><b>SBox Output Resolution</b></td>"
    for sbb in sbb_data:
        html += f"<td>{sbb.get('res_sbb', '')}</td>"
    html += "</tr>"

    # Cabinet Resolution
    html += "<tr><td><b>Cabinet Resolution</b></td>"
    for sbb in sbb_data:
        html += f"<td>{sbb.get('res_cab', '')}</td>"
    html += "</tr>"
    
    html += "</table></div>"

    # --- Cab Info ---
    html += '<div class="section"><h2>Cabinet Information</h2>'
    
    # Summary Table
    html += "<h3>Summary</h3>"
    html += "<table><tr><th>Total Cabs</th><th>Most Common Model</th><th>Most Common Main FW</th><th>Most Common FPGA FW</th><th>Avg Temp</th><th>Max Temp</th><th>Min Temp</th></tr>"
    html += f"<tr><td>{cab_stats.get('count', 0)}</td>"
    html += f"<td>{cab_stats.get('mode_model', '')}</td>"
    html += f"<td>{cab_stats.get('mode_fw_main', '')}</td>"
    html += f"<td>{cab_stats.get('mode_fw_fpga', '')}</td>"
    html += f"<td>{cab_stats.get('temp_avg', '')}</td>"
    
    m_temp = cab_stats.get('temp_max')
    cls = 'class="bg-pink"' if m_temp is not None else ''
    html += f"<td {cls}>{m_temp or ''}</td>"
    html += f"<td>{cab_stats.get('temp_min', '')}</td></tr></table>"
    
    # html += "<h3>Detailed List</h3>"
    # Group by SBox IP
    unique_ips = []
    seen = set()
    for c in cab_data:
        if c['sbb_ip'] not in seen:
            unique_ips.append(c['sbb_ip'])
            seen.add(c['sbb_ip'])
            
    for s_ip in unique_ips:
        sbox_cabs = [c for c in cab_data if c['sbb_ip'] == s_ip]
        cab_count = len(sbox_cabs)
        
        html += f"<h3>SBox: {s_ip} (Total Cabinets: {cab_count})</h3>"
        html += """<table>
        <tr>
            <th>SBox IP</th><th>Group IP</th><th>ID</th><th>SN</th><th>Model</th>
            <th>Main FW</th><th>FPGA FW</th><th>Temp</th><th>Backlight</th>
            <th>Cab CC</th><th>Mod CC</th><th>Pix CC</th><th>Seam</th><th>Video Loc</th>
        </tr>"""
        
        for cab in sbox_cabs:
            row_html = "<tr>"
            row_html += f"<td>{cab['sbb_ip']}</td><td>{cab['group_ip']}</td><td>{cab['cid']}</td>"
            row_html += f"<td>{cab['sn']}</td>"
            
            # Model
            cls = 'class="bg-pink"' if cab['model'] != cab_stats['mode_model'] else ''
            row_html += f"<td {cls}>{cab['model']}</td>"
            
            # FW
            cls = 'class="bg-pink"' if cab['fw_main'] != cab_stats['mode_fw_main'] else ''
            row_html += f"<td {cls}>{cab['fw_main']}</td>"
            
            # FPGA
            cls = 'class="bg-pink"' if cab['fw_fpga'] != cab_stats['mode_fw_fpga'] else ''
            row_html += f"<td {cls}>{cab['fw_fpga']}</td>"
            
            # Temp
            t_val = cab.get('temp')
            t_cls = ""
            if t_val is not None:
                if cab_stats['temp_max'] is not None and t_val == cab_stats['temp_max']:
                    t_cls = 'class="bg-pink"'
                elif t_val > 59:
                    t_cls = 'class="bg-yellow"'
                    
            row_html += f"<td {t_cls}>{t_val or ''}</td>"
            
            row_html += f"<td>{cab['backlight'] or ''}</td>"
            
            # Bools
            for k in ['cc_cab', 'cc_mod', 'cc_pix', 'seam']:
                val = cab.get(k, '')
                cls = 'class="bg-green"' if val == "On" else ''
                row_html += f"<td {cls}>{val}</td>"
            
            row_html += f"<td>{cab.get('video_location', '')}</td>"
                
            row_html += "</tr>"
            html += row_html
        html += "</table>"
        
    html += "</div>"
    
    # --- Layouts ---

    # --- Layouts ---
    html += '<div class="section"><h2>Cabinet Layouts</h2><div class="layout-container">'
    
    for s_ip in sorted(layout_data.keys()):
        cabs = layout_data[s_ip]
        if not cabs: continue
        
        xs = sorted(list(set(c['x_sbb'] for c in cabs)))
        ys = sorted(list(set(c['y_sbb'] for c in cabs)))
        cols = len(xs)
        rows_len = len(ys)
        
        html += f'<div class="sbb-layout"><h3>SBox: {s_ip}</h3>'
        html += f'<div class="grid" style="grid-template-columns: repeat({cols}, 1fr);">'
        
        # Create grid cells
        # We need to iterate row by row, col by col
        for r_idx in range(rows_len):
            for c_idx in range(cols):
                # Find cab at this grid pos
                cell_cab = None
                for c in cabs:
                    if c['x_sbb'] == xs[c_idx] and c['y_sbb'] == ys[r_idx]:
                        cell_cab = c
                        break
                
                if cell_cab:
                    g = cell_cab['group']
                    color_cls = ""
                    if g == 1: color_cls = "bg-green"
                    elif g == 2: color_cls = "bg-violet"
                    elif g == 3: color_cls = "bg-blue"
                    elif g == 4: color_cls = "bg-tan"
                    
                    html += f"""<div class="cab-cell {color_cls}">
                        <strong>ID: {cell_cab['cid']}</strong>
                        <span>G:{g}</span>
                        <span>{cell_cab['x_sbb']}x{cell_cab['y_sbb']}</span>
                    </div>"""
                else:
                    html += '<div class="cab-cell" style="background:#ddd;"></div>'
                    
        html += "</div></div>"
        
    html += "</div></div></body></html>"
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
