@echo off
echo Building LSM Parser CLI Executable...
pyinstaller --clean LSMParser.spec
echo Building LSM Parser GUI Executable...
pyinstaller --clean LSMParserGUI.spec
echo Copying Manual to dist...
echo Copying Manual to dist...
copy LSMParser_Manual.pdf dist\
echo Generating GUI Manual...
python create_gui_manual.py
move /Y LSMParserGUI_Manual.pdf dist\

REM Only pause if run from double-click (cmd /c)
echo %cmdcmdline% | find /i "/c" >nul
if %errorlevel%==0 pause
