import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import os

# Default Config (Should be moved to environment variables or config file)
SMTP_SERVER = os.environ.get('SMTP_SERVER', 'smtp.gmail.com')
SMTP_PORT = int(os.environ.get('SMTP_PORT', 587))
SMTP_USER = os.environ.get('SMTP_USER', '')
SMTP_PASSWORD = os.environ.get('SMTP_PASSWORD', '')

def send_email_report(recipient, cc, subject_from, attachment_path):
    """
    Sends an email with the PDF report attached.
    """
    msg = MIMEMultipart()
    
    # Subject: "From" field from form populates subject as requested
    msg['Subject'] = f"LSM Report from {subject_from}"
    msg['From'] = SMTP_USER or "lsm-parser@example.com"
    msg['To'] = recipient
    
    recipients = [recipient]
    if cc:
        msg['Cc'] = cc
        recipients.append(cc)
        
    body = f"Please find the attached LSM Parser report.\n\nGenerated by LSM Web Parser."
    msg.attach(MIMEText(body, 'plain'))
    
    # Attachment
    if attachment_path and os.path.exists(attachment_path):
        with open(attachment_path, 'rb') as f:
            part = MIMEApplication(f.read(), Name=os.path.basename(attachment_path))
        
        part['Content-Disposition'] = f'attachment; filename="{os.path.basename(attachment_path)}"'
        msg.attach(part)
    
    # Send
    print(f"Connecting to SMTP {SMTP_SERVER}:{SMTP_PORT}...")
    
    if not SMTP_USER or not SMTP_PASSWORD:
        # Mock send if no credentials
        print("WARNING: No SMTP credentials found in environment variables (SMTP_USER/SMTP_PASSWORD). Email not sent.")
        print(f"Mock Email Details:\nTo: {recipients}\nSubject: {msg['Subject']}\nAttachment: {attachment_path}")
        # In a real app we might raise an error, but for dev/demo we print
        if not SMTP_USER:
             raise ValueError("SMTP Credentials not configured. Please set SMTP_USER and SMTP_PASSWORD.")
        return

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(msg['From'], recipients, msg.as_string())
            print("Email sent successfully.")
    except Exception as e:
        print(f"SMTP Error: {e}")
        raise e
